"""empty message

Revision ID: 2724fa25f842
Revises: 4e2d6e398167
Create Date: 2023-12-08 16:16:25.391480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2724fa25f842'
down_revision = '4e2d6e398167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_info_db',
    sa.Column('title', sa.String(length=64), nullable=True, comment='网站标题'),
    sa.Column('subtitle', sa.String(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me_mk', sa.Text(), nullable=True, comment='关于我mk格式'),
    sa.Column('about_me_html', sa.Text(), nullable=True, comment='关于我html格式'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_info_db')
    # ### end Alembic commands ###
