"""'base2'

Revision ID: 63638630f040
Revises: db16661814db
Create Date: 2023-11-29 14:51:00.164382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63638630f040'
down_revision = 'db16661814db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogInfo_db',
    sa.Column('title', sa.String(length=64), nullable=True, comment='网站标题'),
    sa.Column('subtitle', sa.String(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me', sa.Text(), nullable=True, comment='关于我'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogInfo_db')
    # ### end Alembic commands ###
