"""empty message

Revision ID: 6ff03966dd6d
Revises: 63638630f040
Create Date: 2023-12-05 21:42:28.620754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ff03966dd6d'
down_revision = '63638630f040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogInfo_db',
    sa.Column('title', sa.String(length=64), nullable=True, comment='网站标题'),
    sa.Column('subtitle', sa.String(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me', sa.Text(), nullable=True, comment='关于我'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_db', schema=None) as batch_op:
        batch_op.alter_column('replied_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='回复的评论id',
               existing_comment='回复属于某一条评论',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_db', schema=None) as batch_op:
        batch_op.alter_column('replied_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='回复属于某一条评论',
               existing_comment='回复的评论id',
               existing_nullable=True)

    op.create_table('bloginfo_db',
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True, comment='网站标题'),
    sa.Column('subtitle', mysql.VARCHAR(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me', mysql.TEXT(), nullable=True, comment='关于我'),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='id主键'),
    sa.Column('add_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('blogInfo_db')
    # ### end Alembic commands ###
