"""'base1'

Revision ID: db16661814db
Revises: 
Create Date: 2023-11-29 14:43:32.287758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db16661814db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogInfo_db',
    sa.Column('title', sa.String(length=64), nullable=True, comment='网站标题'),
    sa.Column('subtitle', sa.String(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me', sa.Text(), nullable=True, comment='关于我'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bloginfo_db')
    with op.batch_alter_table('attachment_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_token', sa.String(length=36), nullable=True, comment='uuid临时标识'))

    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.drop_constraint('note_tags_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'note_db', ['note_id'], ['id'])

    # ### end Alembic commands ###

